### ISSUE TITLE
Better "Letters guessed" prompt

### ISSUE THREAD

**Issue by arumoy-shome** [shaw-rohit/Hangman#18]
Currently, during the very first iteration we see something like this:
```
Letters guessed: set()
```
Once, the user makes a guess we get something like this:
```
Letters guessed: {'A', 'B'}
```
We should improve the initial prompt to perhaps print this:
```
Letters guessed: {}
```
So that things are consistent.

**Comment by shaw-rohit** [comment]
How about we print the line `Letters guessed: {'A'}` only after a letter has been guessed?

**Comment by arumoy-shome** [comment]
Yes that can work.
