### ISSUE TITLE
Incomplete Game Ending: Final Guessed Word Not Printed

### ISSUE THREAD

**Issue by shrutirao94** [shaw-rohit/Hangman#19]
We should show the completed word at the end at the least so that users can see their correctly guessed word!

OOP ending:

```
It is a city with 9 letters! 
Word: A M S T E R _ A M 
Remaining lives: 6
Letters guessed: {'A', 'O', 'L', 'R', 'S', 'T', 'W', 'E', 'M'}
Please guess a letter: d
This letter is in the word!
Yay! You won the game!
Enter Y to replay the game or any other key to exit:
```

Current Ending:
````
Please guess a letter: a

This letter is in the word!
Word: P E T U N I A
Congratulations! You won the game!
Enter Y to replay the game. Enter any other key to exit.
````

**Comment by shaw-rohit** [comment]
I'm sorry I have to reopen this since the current solution doesn't feel complete.

![image](https://user-images.githubusercontent.com/40485926/80202958-b1e9f300-8626-11ea-9b2d-0be3a77b4c2d.png)

It'll be a bigger problem once we have the graphical hangman in place.

**Comment by Pungent-Paws** [comment]
All right. I found it a bit hard to see the exact issue with the current solution, and I think it would be easier to see how the different discussed solutions compare once a graphical hangman is in place.
