### ISSUE TITLE
Clear Screen is not Cross-Platform Compatible

### ISSUE THREAD

**Issue by shrutirao94** [shaw-rohit/Hangman#23]
`os.system("cls")` occurs in `game.py` on several instances. However, this command is only applicable for windows and does not work on OS X (and perhaps even Linux?) We will require a way to clear screen that works across all platforms!

<img width="637" alt="Screenshot 2020-04-21 at 21 06 30" src="https://user-images.githubusercontent.com/12822003/79903815-08331800-8414-11ea-91b8-fc5f2d89f4d4.png">

**Comment by shaw-rohit** [comment]
Ah, I know the fix! *self-assigns*

**Comment by shrutirao94** [comment]
It's a tasty bug for our report. Just the kind of stuff they'd love to see!

**Comment by shaw-rohit** [comment]
Closing as this has been resolved.
