### ISSUE TITLE
Game feels slow when playing

### ISSUE THREAD

**Issue by shaw-rohit** [shaw-rohit/Hangman#24]
The game feels very slow because of the 1-second sleep delay that has been added throughout the game. This was done to make up for the "clear terminal screen" after letter guesses during the game.

Refactoring the code a bit will help get past the need for the sleep timer.

**Comment by arumoy-shome** [comment]
Perhaps responsiveness of the game can be added as a user requirement? @Pungent-Paws

**Comment by Pungent-Paws** [comment]
I looked into it but didn't see (yet) how to handle this. Might be a bit annoying for the user, but I guess one way would be to ask the user to press something (maybe just space, (`'  '`?)) to continue guessing another letter? This way they can also control themselves for how long they want to be able to see the message to them after their latest guess ( `"You have already guessed this letter! Try again!"`) etc

**Comment by shrutirao94** [comment]
Well in my original code, I had used a `clear_screen()` method that simply printed out blanks. Can we do that? Or can we reduce the delay to 0.5?

**Comment by shrutirao94** [comment]
Also, I hd originally asked for this issue because I didn't know of the added delay. We dont need this issue if the delay is intentional.

**Comment by shaw-rohit** [comment]
Reducing the delay to 0.5 makes a big difference and is the easiest way of getting past this issue.
