### ISSUE TITLE
The sequence of letters guessed doesn't match with the actual sequence of guesses

### ISSUE THREAD

**Issue by shaw-rohit** [shaw-rohit/Hangman#25]
I entered the 5 vowels as guesses in the order - A, E, I, O, U, but the sequence in the list of letters guessed suggests otherwise.

![image](https://user-images.githubusercontent.com/40485926/79913637-3ddffd00-8424-11ea-902c-7ad9873bf979.png)

**Comment by arumoy-shome** [comment]
Interesting, probably to do with how sets work in python?

**Comment by shrutirao94** [comment]
Yes I just realised that this is because of `set()`. It would have reordered based on most efficient positioning. Might have to change that datatype then.
