### ISSUE TITLE
Blackbox testing (own product) - Use Cases 

### ISSUE THREAD

**Issue by Pungent-Paws** [shaw-rohit/Hangman#34]
As far as I can tell, Value-based blackbox testing techniques do not seem as applicable to our product as Model-based techniques. 

All Model-based ones presented in lectures could in theory work, but I think we should at least use the Use Cases method.

**Reason:** 

Use Case models are known to be good at capturing the system's functional reqs from user perspective (which we don't have as much because we did not separate ourselves in to dev / user roles )

Cause-Effect and State Machine models, on the other hand, would overcomplicate things. These are well-suited when there's multi-variable input, which we don't have? 

p.s. Any Blackbox techniques that we don't apply to our own product, we can try to apply to the product we receive from the other group, to still show the grader we learned how to use various methods 

_Edit_
see example of Use-case in Overleaf, which supposedly exposed issue #18 and #25

_Edit2_
Maybe I misunderstood Value-based methods.  I was able to combine Decision table (test of req 10 and 6) with Boundary Testing

_Edit3_
I changed my opnion: I encountered a situation where state machine model would probably have been better than use-case

**Comment by arumoy-shome** [comment]
💯
