### ISSUE TITLE
Leave game

### ISSUE THREAD

**Issue by arumoy-shome** [shaw-rohit/Hangman#4]
As a user, I should be able to exit the game at any given time.

**Comment by shrutirao94** [comment]
We will need a special way of addressing this since users will be required able to enter any character to play the game itself (including Shift + Char)

I suggest as a fun quirk we use vim's exit command `:q`

**Comment by arumoy-shome** [comment]
> I suggest as a fun quirk we use vim's exit command `:q`

👍

**Comment by Pungent-Paws** [comment]
Just pointing out that the solution to this would also solve the following problem (similar, hence I didn't think I should create a separate issue out of it):  
![bug25](https://user-images.githubusercontent.com/44074078/80036143-7ac5f580-84f1-11ea-9b7c-b23200132d68.png)
Pressing any key (I pressed the letter 'l') actually starts a new game like 'Y' does.

**Comment by arumoy-shome** [comment]
@Pungent-Paws I don't think you have the latest code, `Letters Guessed` was changed to a `set` in my OOP implementation but here in the screenshot I see a list?

**Comment by Pungent-Paws** [comment]
> @Pungent-Paws I don't think you have the latest code, `Letters Guessed` was changed to a `set` in my OOP implementation but here in the screenshot I see a list?

Yes in the latest code (pulled from remote master) Letters Guessed is a set indeed, but I changed it to a list (see latest commit to my PR) to address issue #25. Sorry I should have made that clear!

**Comment by arumoy-shome** [comment]
>Yes in the latest code (pulled from remote master) Letters Guessed is a set indeed, but I changed it to a list (see latest commit to my PR) to address issue #25. Sorry I should have made that clear!

Okay, then the issue must be in your feature branch :)

**Comment by shrutirao94** [comment]
Do we need this? Anyway one can quit the game by pressing `Ctrl+C`. We can just mention that somewhere.

**Comment by shaw-rohit** [comment]
> Do we need this? Anyway one can quit the game by pressing `Ctrl+C`. We can just mention that somewhere.

We can mention this in the game instructions!
